version: "3.8"
services:
  setimarine_blazor:
    build:
      context: .
      dockerfile: SetiMarine.Web/Dockerfile
    container_name: setimarine_blazor
    ports:
      - "9092:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres_setimarine
    restart: unless-stopped

  postgres_setimarine:
    image: postgres:16
    container_name: postgres_setimarine
    environment:
      POSTGRES_DB:       setimarine
      POSTGRES_USER:     setimarine
      POSTGRES_PASSWORD: SetiMarine@2026
    ports:
      - "5436:5432"
    volumes:
      - setimarine_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  setimarine_pgdata:
