// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SetiMarine.Infrastructure.Data;

#nullable disable

namespace SetiMarine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412002448_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_clientes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cfg_configuracoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_contratos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Embarcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BocaMetros")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CaladoMetros")
                        .HasColumnType("numeric");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ComprimentoMetros")
                        .HasColumnType("numeric");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("VagaFixaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VagaFixaId");

                    b.ToTable("mar_embarcacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnderecoCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("InstanciaWhatsApp")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlanoVenceEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("sis_empresas", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.HistoricoMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Em")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("mar_historico_movimentacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgendadoPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("OrigemWhatsApp")
                        .HasColumnType("text");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_movimentacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("mar_ordens_servico", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteEmbarcacoes")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("LinkPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recursos")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("cfg_planos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.SessaoAtiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaAtividadeEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("sis_sessoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TemaEscuro")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Email")
                        .IsUnique();

                    b.ToTable("sis_usuarios", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BocaMaxMetros")
                        .HasColumnType("numeric");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ComprimentoMaxMetros")
                        .HasColumnType("numeric");

                    b.Property<int?>("EmbarcacaoAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Largura")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("PosX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PosY")
                        .HasColumnType("numeric");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoAtualId");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique();

                    b.ToTable("mar_vagas", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Embarcacao");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Embarcacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Embarcacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "VagaFixa")
                        .WithMany()
                        .HasForeignKey("VagaFixaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("VagaFixa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.HistoricoMovimentacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("Historico")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embarcacao");

                    b.Navigation("Responsavel");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Embarcacao");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "EmbarcacaoAtual")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoAtualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmbarcacaoAtual");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Embarcacoes");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
