// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SetiMarine.Infrastructure.Data;

#nullable disable

namespace SetiMarine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530003623_AddAgendamentoUso")]
    partial class AddAgendamentoUso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SetiMarine.Domain.Entities.AgendamentoUso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHoraPreparacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataHoraUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("MinutosAntecedencia")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TipoUso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_agendamentos_uso", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_checklist_templates", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("ChecklistTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.ToTable("mar_checklist_template_itens", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_clientes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cfg_configuracoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_contratos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Corredor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("TamanhoMaxPes")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_corredores", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Embarcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BocaMetros")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CaladoMetros")
                        .HasColumnType("numeric");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ComprimentoMetros")
                        .HasColumnType("numeric");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("VagaFixaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VagaFixaId")
                        .IsUnique();

                    b.ToTable("mar_embarcacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnderecoCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("InstanciaWhatsApp")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("text");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlanoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PlanoVenceEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlanoId");

                    b.ToTable("sis_empresas", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.FotoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("EhAvaria")
                        .HasColumnType("boolean");

                    b.Property<int>("RegistroServicoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TiradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistroServicoId");

                    b.ToTable("mar_fotos_servico", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.HistoricoMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Em")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("StatusAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("mar_historico_movimentacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgendadoPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("OrigemWhatsApp")
                        .HasColumnType("text");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_movimentacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ValorEstimado")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorFinal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("mar_ordens_servico", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int?>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PrevisaoConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("mar_pedidos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataDevolucaoPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HorasAluguel")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusEmprestimo")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("mar_pedido_itens", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("mar_pedido_servicos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoUso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("MensagemOriginal")
                        .HasColumnType("text");

                    b.Property<int?>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("mar_pedidos_uso", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Destaque")
                        .HasColumnType("boolean");

                    b.Property<int>("LimiteEmbarcacoes")
                        .HasColumnType("integer");

                    b.Property<int>("LimiteUsuarios")
                        .HasColumnType("integer");

                    b.Property<string>("LinkPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("Recursos")
                        .HasColumnType("text");

                    b.Property<string>("TextoBotao")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("cfg_planos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PlanoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Mensalidade")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("cfg_planos_contrato", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PlanoContratoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("PlanoContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("TipoServicoConfigId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanoContratoId");

                    b.HasIndex("TipoServicoConfigId");

                    b.ToTable("cfg_plano_contrato_servicos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Alugavel")
                        .HasColumnType("boolean");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecoAluguelDia")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecoAluguelHora")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("numeric");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_produtos", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.RegistroServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgendadoPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoServicoConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("VagaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("MovimentacaoId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("TipoServicoConfigId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_registros_servico", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.RegistroServicoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChecklistTemplateItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("RegistroServicoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateItemId");

                    b.HasIndex("RegistroServicoId");

                    b.ToTable("mar_registro_servico_itens", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.SessaoAtiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaAtividadeEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sis_sessoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.TipoServicoConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int?>("ChecklistTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DuracaoHoras")
                        .HasColumnType("numeric");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int>("FrequenciaDias")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorPadrao")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mar_tipos_servico_config", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TemaEscuro")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Email")
                        .IsUnique();

                    b.ToTable("sis_usuarios", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BocaMaxMetros")
                        .HasColumnType("numeric");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ComprimentoMaxMetros")
                        .HasColumnType("numeric");

                    b.Property<int?>("CorredorId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmbarcacaoAtualId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Largura")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LarguraMaxPes")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("PosX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PosY")
                        .HasColumnType("numeric");

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TamanhoMaxPes")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorredorId");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique();

                    b.ToTable("mar_vagas", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.VagaEmbarcacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("EmbarcacaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SaidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcacaoId");

                    b.HasIndex("VagaId");

                    b.ToTable("mar_vaga_embarcacoes", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.VendaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataDevolucaoPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusAluguel")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("mar_vendas_produto", (string)null);
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.AgendamentoUso", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId");

                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Embarcacao");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Itens")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Clientes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Embarcacao");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Corredor", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Embarcacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Embarcacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "VagaFixa")
                        .WithOne("EmbarcacaoAtual")
                        .HasForeignKey("SetiMarine.Domain.Entities.Embarcacao", "VagaFixaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("VagaFixa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.FotoServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.RegistroServico", "RegistroServico")
                        .WithMany("Fotos")
                        .HasForeignKey("RegistroServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroServico");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.HistoricoMovimentacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("Historico")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embarcacao");

                    b.Navigation("Responsavel");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.OrdemServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Embarcacao");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId");

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.Navigation("Cliente");

                    b.Navigation("Embarcacao");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Servicos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pedido");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PedidoUso", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany()
                        .HasForeignKey("MovimentacaoId");

                    b.Navigation("Cliente");

                    b.Navigation("Embarcacao");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PlanoContrato", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PlanoContratoServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.PlanoContrato", "PlanoContrato")
                        .WithMany("Servicos")
                        .HasForeignKey("PlanoContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.TipoServicoConfig", "TipoServico")
                        .WithMany()
                        .HasForeignKey("TipoServicoConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanoContrato");

                    b.Navigation("TipoServico");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Produto", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.RegistroServico", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany()
                        .HasForeignKey("MovimentacaoId");

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId");

                    b.HasOne("SetiMarine.Domain.Entities.TipoServicoConfig", "TipoServicoConfig")
                        .WithMany()
                        .HasForeignKey("TipoServicoConfigId");

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId");

                    b.Navigation("Embarcacao");

                    b.Navigation("Movimentacao");

                    b.Navigation("Responsavel");

                    b.Navigation("TipoServicoConfig");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.RegistroServicoItem", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.ChecklistTemplateItem", "ChecklistTemplateItem")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateItemId");

                    b.HasOne("SetiMarine.Domain.Entities.RegistroServico", "RegistroServico")
                        .WithMany("Itens")
                        .HasForeignKey("RegistroServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplateItem");

                    b.Navigation("RegistroServico");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.SessaoAtiva", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.TipoServicoConfig", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("TiposServico")
                        .HasForeignKey("ChecklistTemplateId");

                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Corredor", "Corredor")
                        .WithMany("Vagas")
                        .HasForeignKey("CorredorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SetiMarine.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corredor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.VagaEmbarcacao", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Embarcacao", "Embarcacao")
                        .WithMany()
                        .HasForeignKey("EmbarcacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Vaga", "Vaga")
                        .WithMany("EmbarcacoesNaVaga")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Embarcacao");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.VendaProduto", b =>
                {
                    b.HasOne("SetiMarine.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SetiMarine.Domain.Entities.Produto", "Produto")
                        .WithMany("Transacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetiMarine.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("TiposServico");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Embarcacoes");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Corredor", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Usuarios");

                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.PlanoContrato", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.RegistroServico", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SetiMarine.Domain.Entities.Vaga", b =>
                {
                    b.Navigation("EmbarcacaoAtual");

                    b.Navigation("EmbarcacoesNaVaga");
                });
#pragma warning restore 612, 618
        }
    }
}
